# Generated by Django 3.2 on 2023-01-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230128_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.IntegerField(),
        ),
    ]
