# Generated by Django 3.2 on 2023-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.IntegerField(),
        ),
    ]
