# Generated by Django 3.2 on 2023-01-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230129_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='difference',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
