# Generated by Django 3.2 on 2023-01-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_player_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='difference',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
