# Generated by Django 3.2 on 2023-01-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230130_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user',
            new_name='user_id',
        ),
    ]
