# Generated by Django 3.2 on 2023-05-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230521_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
